version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: pub
    directories:
      - /
      - /example
    schedule:
      interval: weekly
      day: monday
    groups:
      pub-dependencies:
        patterns: ["*"]
